const express = require('express');
const app = express();
const bodyParser = require('body-parser');
const cors = require('cors');
const getuserfiles = require('./api/getuserfiles');
const multer = require('multer');
const upload = multer();

app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());
app.use(upload.array()); 
app.use(express.static('public'));
app.use(cors());
//to handle issue of cors
app.use((req, res, next) => {
    res.header('Access-Control-Allow-Origin', '*'); 
    res.header(
        'Access-Control-Allow-Headers', 
        'Origin, X-Requested-With, Content-Type, Accept, Authorization'
    );
    if(req.method === 'OPTIONS'){
        res.header('Access-Control-Allow-Methods', 'POST, GET, PATCH, DELETE, OPTIONS');
        return res.status(200).json({});
    }
    next();
});


app.use('/api/getuserfiles',getuserfiles);

//handle not implemented url
app.use((req, res, next) =>{
    const err = new Error('Not Found');
    err.status = 400;
    next(err);
});

//handlle exceptions
app.use(function (err, req, res, next) {
    var errorCode = err.status || 500;
  
    // Set locals.
    res.locals.message = err.message;
    res.locals.error = errorCode;
  
    res.status(errorCode);
  
    if (!err.status) {
      try {
        // To see if the message is a JSON object which is generated by developers.
        JSON.parse(err.message);
  
        // Developer exceptions are JSON objects.
        res.send(err.message);
      } catch {
        // API exceptions. They are not JSON objects.
        res.send({ result: 'error', message: err.message });
      }
    } else {
      // Express exceptions.
      res.send({ result: err.status, message: err.message });
    }
  });

module.exports = app;
